UXG-1237 adds general settings template
idxbroker/wordpress-plugin pull request #189
Opened 2021-02-18 17:29 UTC by nicmarson

[UXG-1237](http://jira.hq.idx.org/browse/UXG-1237) adds general settings template and state

2021-02-18 19:15 UTC, ErikIDX requested changes

2021-02-18 19:15 UTC, ErikIDX commented on src/vue/backend/src/store/common/store/mutationTypes.js
> +export const SET_ITEM = 'SET_ITEM'
The path `store/common/store` is kinda funky, not not keep it up a level? Same with mutations.js

2021-02-18 19:15 UTC, ErikIDX commented on src/vue/backend/src/templates/GeneralSettings.vue
> +            updateFrequencyOptions: [
Missing associated values

2021-02-18 19:15 UTC, ErikIDX commented on src/vue/backend/src/store/modules/general/index.js
> +    updateFrequency: { name: '3 minutes' },
Probably don't want to pass around display values as your state identifiers

2021-02-18 21:40 UTC, sgreenl5 commented on src/vue/backend/src/templates/GeneralSettings.vue
> +                uniqueID="update-frequency"
You won't need the unique ID in the custom select once that is merged in

2021-02-18 22:07 UTC, sgreenl5 approved these changes
Looks good. There is one thing in the routes/index.js that you don't need in this PR (expanded:true), but its going to be added in another PR so I'm fine with letting it merge in here 👍

2021-02-18 22:14 UTC, sgreenl5 requested changes
Forgot to update your frequency options list, added it to the ticket so you can update it here

2021-02-18 22:14 UTC, sgreenl5 commented on src/vue/backend/src/templates/GeneralSettings.vue
> +            updateFrequencyOptions: [
Here is the list of frequency options. I will update the ticket
<img width="149" alt="Screen Shot 2021-02-18 at 2 11 07 PM" src="https://user-images.githubusercontent.com/25048313/108428439-6d51c880-71f3-11eb-9d3d-241844356bd9.png">

2021-02-18 22:39 UTC, sgreenl5 commented on src/vue/backend/src/templates/GeneralSettings.vue
> +                @input="generalSettingsStateChange({ key: 'wrapperName', value: $event })"
This seems like it could send a lot of unnecessary updates, lets chat about debouncing the input

2021-02-18 22:41 UTC, sgreenl5 commented on src/vue/backend/src/templates/GeneralSettings.vue
> +    --space-4: 16px;
It appears that you have a lot of extra variables in here that you aren't using

2021-02-18 22:41 UTC, sgreenl5 commented on src/vue/backend/src/store/modules/routes/index.js
> +    expanded: true
This isn't used in this PR

2021-02-19 16:47 UTC, sgreenl5 requested changes

2021-02-19 16:47 UTC, sgreenl5 commented on src/vue/backend/src/templates/GeneralSettings.vue
> +                this.$emit('keyPress', e)
This is just emitting an event, you need to call the state change action here instead

2021-02-19 16:47 UTC, sgreenl5 commented on src/vue/backend/src/templates/GeneralSettings.vue
> +            console.log(e.target.value)
Left console long

2021-02-19 16:47 UTC, sgreenl5 commented on src/vue/backend/src/templates/GeneralSettings.vue
> +                id="update-frequency"
Custom select already has a label in the component, can you run this through with a screen reader and verify there isn't repetition?

2021-02-19 17:45 UTC, sgreenl5 commented on src/vue/backend/src/templates/GeneralSettings.vue
> +            }, this.debounceTimeout)
Where is debounceTimeout being defined?

2021-02-19 18:29 UTC, sgreenl5 approved these changes

2021-02-19 18:56 UTC, sgreenl5 commented on src/vue/backend/src/templates/GeneralSettings.vue
> +                @keyup="debounceInput($event)"
It looks like the idx form input component takes care of this by emitting a "change" event on enter or blur. That removes our need to use debounce. 
```
@change="generalSettingsStateChange(...)"
```
http://bitbucket.hq.idx.org/projects/PROJ/repos/vuecomponentlibrary/browse/src/components/Atoms/Forms/FormInput.vue#33

2021-02-19 20:51 UTC, sgreenl5 commented on src/vue/backend/src/templates/GeneralSettings.vue
> +                @change="generalSettingsStateChange('wrapperName', $event)"
Missing key value syntax
```
@change="generalSettingsStateChange({key: 'wrapperName', value: $event.target.value })"
```

2021-02-19 21:42 UTC, ErikIDX requested changes

2021-02-19 21:42 UTC, ErikIDX commented on src/vue/backend/src/store/modules/general/index.js
> +    wrapperName: 'idx-wp-'
In the existing plugin, the default wrapper name is unset, so this should be an empty string

2021-02-19 21:44 UTC, ErikIDX approved these changes

2021-02-19 21:44 UTC, merged