UXG-1244: adds advanced listing settings tab content
idxbroker/wordpress-plugin pull request #198
Opened 2021-02-25 19:41 UTC by nicmarson

http://jira.hq.idx.org/browse/UXG-1244

2021-02-25 20:10 UTC, sgreenl5 requested changes
Some implementation errors, and you're missing css to match the design (line breaks, bold in words), but overall looking pretty good.

Additionally, the toggles are not the correct design. However, in my omnibar PR I have a global form style sheet that I can use to update this once mine is merged in.

2021-02-25 20:10 UTC, sgreenl5 commented on src/vue/backend/src/templates/ListingsAdvanced.vue
> +                @change="listingsSettingsStateChange({ key: formShortcode, value: $event.target.value })"
Key needs to be a string, otherwise it does not update the state correctly. Same on lines 66, 78, and 87

2021-02-25 20:10 UTC, sgreenl5 commented on src/vue/backend/src/templates/ListingsAdvanced.vue
> +            <idx-block className="control-label"><strong>Google Maps</strong> Listings can be automatically mapped if a latitude and longitude is provided. A Google Maps API Key is required - click h
Lets add the link to the google maps api. This is the one currently in our settings implementation
`https://developers.google.com/maps/documentation/javascript/get-api-key`

2021-02-25 20:10 UTC, sgreenl5 commented on src/vue/backend/src/templates/ListingsAdvanced.vue
> +<template>
Form is missing the line breaks shown in the design

2021-02-26 16:15 UTC, sgreenl5 submitted a review, later dismissed

2021-02-26 16:53 UTC, sgreenl5 commented on src/vue/backend/src/templates/ListingsAdvanced.vue
> +            <idx-block className="control-label"><strong>Google Maps</strong> Listings can be automatically mapped if a latitude and longitude is provided. A Google Maps API Key is required - <a href
This should open in a new tab,

2021-02-26 16:54 UTC, ralls submitted a review, later dismissed
looks good @nicmarson ✅

2021-02-26 17:21 UTC, ErikIDX approved these changes

2021-02-26 17:41 UTC, sgreenl5 approved these changes

2021-02-26 17:58 UTC, ralls approved these changes
👍

2021-02-26 18:05 UTC, merged