UXG-1272 listings general guided setup page
idxbroker/wordpress-plugin pull request #212
Opened 2021-03-03 22:10 UTC by nicmarson

http://jira.hq.idx.org/browse/UXG-1272

2021-03-03 23:01 UTC, sgreenl5 requested changes
The save actions are inside of the `general` module's actions file, and instead should be in their corresponding actions file. The `general` module is for routes `guided-setup/connect/general` and `settings/general` only

2021-03-04 18:31 UTC, sgreenl5 approved these changes

2021-03-05 17:55 UTC, sgreenl5 requested changes

2021-03-05 17:55 UTC, sgreenl5 commented on src/vue/backend/src/mixins/guidedSetup.js
> +            await this.saveGeneralListingsSettings()
This is too specific of an api call an cannot be reused, for now you can take this piece and abstract it to the view level. So the view would look like
```
@continue="something"

async something () {
    await this.savegeneralsettings()
    this.goContinue()
}
```

2021-03-05 17:55 UTC, sgreenl5 commented on src/vue/backend/src/views/guided-setup/ListingsGeneral.vue
> +            <ListingsGeneral/>
This does not match the new form content flow implementation, and is not adjusting the state

2021-03-05 17:55 UTC, sgreenl5 commented on src/vue/backend/src/views/guided-setup/ListingsGeneral.vue
> +            enabled: state => state.listingsSettings.enabled,
What are you using enabled for?

2021-03-05 22:26 UTC, sgreenl5 commented on src/vue/backend/src/views/guided-setup/ListingsGeneral.vue
> +        async goContinue () {
You already have the goContinue defined from your mixin

2021-03-05 22:28 UTC, sgreenl5 approved these changes

2021-03-05 22:29 UTC, ralls approved these changes

2021-03-05 22:39 UTC, merged