UXG-1324 match design
idxbroker/wordpress-plugin pull request #254
Opened 2021-03-12 15:06 UTC by nicmarson

http://jira.hq.idx.org/browse/UXG-1324

2021-03-12 15:12 UTC, nicmarson commented
![axe-score](https://user-images.githubusercontent.com/1541291/110958858-fbf0cb80-8301-11eb-99ea-784fbf43ee1a.png)
I ran axe before and after this PR, and there was a big improvement, 41 issues down to 14. The remaining 14 issues are from missing alt tags for the nav icons, and color contrast issues.

2021-03-12 15:34 UTC, sgreenl5 requested changes

2021-03-12 15:34 UTC, sgreenl5 commented on src/vue/backend/src/views/children/generalContentTab.vue
> +            size="lg"
The button sizes are not wide enough in all standalone pages, should be 155w

2021-03-12 15:34 UTC, sgreenl5 commented on src/vue/backend/src/templates/GuidedSetupContentCard.vue
>      }
The link button does not match design, in implementation it has blue color and a border/button color. In the design, it is black text

2021-03-12 15:34 UTC, sgreenl5 commented on src/vue/backend/src/templates/GuidedSetupContentCard.vue
>      }
Back button is not wide enough, should be 155px

2021-03-12 20:39 UTC, sgreenl5 approved these changes

2021-03-16 16:36 UTC, ErikIDX approved these changes

2021-03-16 17:01 UTC, merged