UXG-1307 standalone settings feedback
idxbroker/wordpress-plugin pull request #279
Opened 2021-03-19 19:59 UTC by nicmarson

http://jira.hq.idx.org/browse/UXG-1307

2021-03-19 20:33 UTC, sgreenl5 requested changes
Looks good! Remove some of those comments, and add the scroll behavior, and this is set! Great job 👍

2021-03-19 20:33 UTC, sgreenl5 commented on src/vue/backend/src/mixins/pageGuard.js
> +            console.log('scroll')
Test code

2021-03-19 20:33 UTC, sgreenl5 commented on src/vue/backend/src/views/children/advancedContentTab.vue
> +                // To do: user feedback
You can remove the comment here

2021-03-19 20:33 UTC, sgreenl5 commented on src/vue/backend/src/views/children/generalContentTab.vue
> +                // To do: user feedback
You can remove the comment

2021-03-19 20:33 UTC, sgreenl5 commented on src/vue/backend/src/views/children/idxContentTab.vue
> +                // To do: user feedback
You can remove the comment

2021-03-19 20:33 UTC, sgreenl5 commented on src/vue/backend/src/views/settings/Listings.vue
> +                // To do: user feedback
You can remove the comment

2021-03-19 20:33 UTC, sgreenl5 commented on src/vue/backend/src/views/settings/Omnibar.vue
> +                    // To do: user feedback
Comment

2021-03-19 20:33 UTC, sgreenl5 commented on src/vue/backend/src/views/settings/SocialPro.vue
> +                    // To do: user feedback
Comment

2021-03-19 20:33 UTC, sgreenl5 commented on src/vue/backend/src/mixins/pageGuard.js
> +            window.scrollTo(0, 0)
This is a little jumpy, lets add smooth behavior

2021-03-22 14:23 UTC, sgreenl5 requested changes

2021-03-22 14:23 UTC, sgreenl5 commented on src/vue/backend/src/components/Notification.vue
> +.notification {
This is missing the transition css to make it fade in and out

2021-03-22 15:21 UTC, sgreenl5 approved these changes

2021-03-22 16:28 UTC, ErikIDX approved these changes

2021-03-22 18:06 UTC, merged